### PR TITLE
directx 11 (or any 64bit) changes

### PR DESCRIPTION
**Pull request by Icehunter**
https://github.com/Icehunter/ffxivapp/releases/tag/AnyCPU-DX9-DX11

Test build for those interested.

### CODE REVIEW

**Comment by Hazado** [comment]
Okay, tried the new version. Finds FX11. Nothing is working plugin wise though. 
Error log below

2015-07-10 17:37:29.7113 Unable to cast object of type 'System.Text.RegularExpressions.Group' to type 'System.IConvertible'.
2015-07-10 17:37:29.7113 Unable to cast object of type 'System.Text.RegularExpressions.Group' to type 'System.IConvertible'.
2015-07-10 17:38:32.8553 Exception has been thrown by the target of an invocation.
Then the above error is shown like 100 times.

**Comment by Icehunter** [comment]
Did it give you a stack trace to where that was?

**Comment by Hazado** [comment]
Tell me where to look and I will. I turned on the Enable Logging with NLog. Is there somewhere else I need to look?

**Comment by Icehunter** [comment]
Grab this:

http://www.log4view.com/download/current-version/

Then run it, add a new udp listener on port 9994. When you start the app it sends logs out into that. I'm not running in debug mode; but running the app directly doesn't produce those errors.

**Comment by Hazado** [comment]
Okay its one of the plugins

**Comment by Icehunter** [comment]
I have all mine loaded, does it say which one?

**Comment by Hazado** [comment]
No, im loading them one at a time until I get the error

**Comment by Icehunter** [comment]
Working on the chatlog right now to get that working to start with in dx11 ^^

**Comment by Hazado** [comment]
Okay, uninstalling and reinstalling seemed to made that error go away, so no clue

**Comment by Hazado** [comment]
Hmm, okay having FFXIV-APP started before you start FFXIV DX11 makes the error happen. Restarting the FFXIV-App client makes the error not happen. 

18:10:46.7310000	ERROR	FFXIVAPP.Client.App	Unable to cast object of type 'System.Text.RegularExpressions.Group' to type 'System.IConvertible'.	
Happens when you try to attach the client by selecting it manually then clicking the button

**Comment by Icehunter** [comment]
Okay so that's in the regex checking the ID in box; I'll do better error checking on that.

**Comment by Icehunter** [comment]
So I'm having issues... I can find the signature in RAM using CheatEngine however the memory limit I can scan to is much smaller. So I'm not able to reach the upper limit :(

**Comment by Icehunter** [comment]
I'm also compiling the application with only 64bit support; and still nothing.

**Comment by Icehunter** [comment]
Everything is forced (so far) to be compiled in x64. Working on way to read the ram in 32bit; but it's not being very friendly.

**Comment by Icehunter** [comment]
Added a test build for any cpu and dx9/11

https://github.com/Icehunter/ffxivapp/releases/tag/AnyCPU-DX9-DX11

**Pull request merged**
