### PR TITLE
proposed 2.4 changes

### PR DESCRIPTION
**Pull request by Icehunter**
@violet1986 I understand the Chinese client recently got patch 2.4. Did anything change? These are my proposed changes to the memory locations based on what they were in 2.4 for our client.

Let me know if they don't work at all :)

### CODE REVIEW

**Comment by violet1986** [comment]
hi Ryan,
The time of 2.4 version release is not pronounced yet, maybe late in March or at the beginning of April. I'll let you know if the release date is out.

Thanks,
Violet

**Comment by Icehunter** [comment]
Oh okay!

I saw the new graphic here: http://ff.sdo.com/web6/index/index.html and thought it came out already.

I'll look forward to getting that working when it comes. We are getting the first expansion in June so that's going to be interesting o.O

**Comment by violet1986** [comment]
Hi Ryan,
2.4 will come at April 2nd for Chinese client:)

Thanks,
Violet

**Comment by violet1986** [comment]
Sorry, 2.4 will come at April Fool's day in Beijing time :)
http://ff.sdo.com/web6/news/newsDetail.asp?id=240933#1



在 2015年3月24日，上午9:24，Ryan Wilson <notifications@github.com> 写道：



Oh okay!

I saw the new graphic here: http://ff.sdo.com/web6/index/index.html and thought it came out already.

I'll look forward to getting that working when it comes. We are getting the first expansion in June so that's going to be interesting o.O

**Comment by violet1986** [comment]
Hi Ryan, I've tested this branch and seems everything is ok. Would you please merge it in? Thanks a lot

**Comment by Icehunter** [comment]
Released and thanks!!!

**Comment by Icehunter** [comment]
I just updated my website to make the forum and main site integrated, I'm
sorry you will have to register again.

Also! I added "network" parsing. I'll be making an update shortly to let
you select the interface but what that means is you can watch the network
packets and use that to parse instead. Just working on the structure of
some of the items.

This will match how act is reading the data as well :)

**Pull request merged**
